"""Oracle Forms runtime: names that exist only in the Forms runtime, never in the database.

A compiled FMB resolves a routine name in this order: the form's own program
units, then the Forms built-ins (standalone subprograms and built-in packages),
and only then the database. So a call to a name listed here - not shadowed by a
local program unit and not schema-qualified - is always the Forms built-in: it
can never run in an anonymous Oracle block. This is the Forms language
definition, not a guess from a name; organisation-specific Forms-side routines
belong in the reviewed framework catalog (forms_runtime_calls).

Kinds decide what may happen to a trigger made only of such calls:
  ui      screen, navigation, items/records in the form buffer, windows, alerts,
          timers, lists, in-memory record groups, parameter lists, menus;
  data    the standard Forms data operations, replaced by the generated CRUD
          endpoints and the frontend steps (executeQuery, commit, ...);
  server  SQL, reports, OS commands, files, OLE/Java or other triggers run through
          the Forms runtime: manual work, never frontend-only.
"""
from __future__ import annotations

DATA = set('''EXECUTE_QUERY ENTER_QUERY COUNT_QUERY ABORT_QUERY COMMIT_FORM POST CLEAR_FORM CLEAR_BLOCK
 EXIT_FORM CLEAR_RECORD CREATE_RECORD DELETE_RECORD DUPLICATE_RECORD LOCK_RECORD NEXT_SET'''.split())

SERVER = set('''FORMS_DDL POPULATE_GROUP POPULATE_GROUP_WITH_QUERY CREATE_GROUP_FROM_QUERY POPULATE_TREE
 EXECUTE_TRIGGER DO_KEY CALL_INPUT HOST USER_EXIT RUN_PRODUCT RUN_REPORT_OBJECT REPORT_OBJECT_STATUS
 COPY_REPORT_OBJECT_OUTPUT CANCEL_REPORT_OBJECT SET_REPORT_OBJECT_PROPERTY GET_REPORT_OBJECT_PROPERTY
 FIND_REPORT_OBJECT LOGON LOGOUT LOGON_SCREEN ISSUE_ROLLBACK ISSUE_SAVEPOINT GENERATE_SEQUENCE_NUMBER
 ENFORCE_COLUMN_SECURITY SELECT_RECORDS FETCH_RECORDS INSERT_RECORD UPDATE_RECORD CHECK_RECORD_UNIQUENESS
 CREATE_QUERIED_RECORD READ_IMAGE_FILE WRITE_IMAGE_FILE READ_SOUND_FILE WRITE_SOUND_FILE GET_FILE_NAME
 ACTIVATE_SERVER CLOSE_SERVER EXEC_VERB INITIALIZE_CONTAINER SERVER_ACTIVE CALL_OLE CALL_OLE_CHAR
 CALL_OLE_NUM CALL_OLE_OBJ CALL_OLE_VAR CREATE_OLEOBJ ADD_OLEARGS INIT_OLEARGS RELEASE_OBJ SET_OLE
 GET_OLE_CHAR GET_OLE_NUM GET_OLE_OBJ GET_OLE_VAR GET_OLE_MEMBERID GET_INTERFACE_POINTER CREATE_VAR
 DESTROY_VARIANT SET_VAR TO_VARIANT PTR_TO_VAR VARPTR_TO_VAR VAR_TO_CHAR VAR_TO_NUMBER VAR_TO_DATE
 VAR_TO_OBJ VAR_TO_TABLE VAR_TO_VARPTR OLEVAR_EMPTY LAST_OLE_ERROR LAST_OLE_EXCEPTION GET_VERB_COUNT
 GET_VERB_NAME FIND_OLE_VERB'''.split())

UI = set('''BELL BREAK BLOCK_MENU CHECKBOX_CHECKED CLEAR_EOL CLEAR_ITEM CLEAR_LIST CLEAR_MESSAGE CLOSE_FORM
 CONVERT_OTHER_VALUE COPY COPY_REGION CUT_REGION PASTE_REGION SELECT_ALL CREATE_GROUP ADD_GROUP_COLUMN
 ADD_GROUP_ROW DELETE_GROUP DELETE_GROUP_ROW CREATE_PARAMETER_LIST ADD_PARAMETER DELETE_PARAMETER
 DESTROY_PARAMETER_LIST GET_PARAMETER_LIST GET_PARAMETER_ATTR SET_PARAMETER_ATTR CREATE_TIMER DELETE_TIMER
 SET_TIMER FIND_TIMER DEBUG_MODE DEFAULT_VALUE DISPATCH_EVENT DISPLAY_ERROR DISPLAY_ITEM DOWN UP
 DUPLICATE_ITEM EDIT_TEXTITEM ENTER ERASE FIRST_RECORD LAST_RECORD NEXT_RECORD PREVIOUS_RECORD GO_RECORD
 GO_BLOCK GO_ITEM GO_FORM NEXT_BLOCK PREVIOUS_BLOCK NEXT_ITEM PREVIOUS_ITEM NEXT_FORM PREVIOUS_FORM
 NEXT_KEY CALL_FORM OPEN_FORM NEW_FORM FIND_ALERT FIND_BLOCK FIND_CANVAS FIND_COLUMN FIND_EDITOR FIND_FORM
 FIND_GROUP FIND_ITEM FIND_LOV FIND_MENU_ITEM FIND_RELATION FIND_TAB_PAGE FIND_VA FIND_VIEW FIND_WINDOW
 GET_APPLICATION_PROPERTY GET_BLOCK_PROPERTY GET_CANVAS_PROPERTY GET_CUSTOM_PROPERTY GET_FORM_PROPERTY
 GET_GROUP_CHAR_CELL GET_GROUP_DATE_CELL GET_GROUP_NUMBER_CELL GET_GROUP_RECORD_NUMBER GET_GROUP_ROW_COUNT
 GET_GROUP_SELECTION GET_GROUP_SELECTION_COUNT GET_ITEM_INSTANCE_PROPERTY GET_ITEM_PROPERTY
 GET_LIST_ELEMENT_COUNT GET_LIST_ELEMENT_LABEL GET_LIST_ELEMENT_VALUE GET_LOV_PROPERTY GET_MENU_ITEM_PROPERTY
 GET_MESSAGE GET_RADIO_BUTTON_PROPERTY GET_RECORD_PROPERTY GET_RELATION_PROPERTY GET_TAB_PAGE_PROPERTY
 GET_TREE_NODE_PARENT GET_TREE_NODE_PROPERTY GET_TREE_PROPERTY GET_TREE_SELECTION GET_VA_PROPERTY
 GET_VIEW_PROPERTY GET_WINDOW_PROPERTY HELP HIDE_MENU HIDE_VIEW HIDE_WINDOW ID_NULL IMAGE_SCROLL IMAGE_ZOOM
 ITEM_ENABLED LIST_VALUES MENU_CLEAR_FIELD MENU_NEXT_FIELD MENU_PARAMETER MENU_PREVIOUS_FIELD MENU_REDISPLAY
 MENU_SHOW_KEYS MESSAGE MOVE_WINDOW NAME_IN NEXT_MENU_ITEM PAUSE PLAY_SOUND POPULATE_GROUP_FROM_TREE
 POPULATE_LIST PREVIOUS_MENU PREVIOUS_MENU_ITEM PRINT QUERY_PARAMETER RECALCULATE REDISPLAY
 REPLACE_CONTENT_VIEW REPLACE_MENU RESET_GROUP_SELECTION RESIZE_WINDOW RETRIEVE_LIST SCROLL_DOWN SCROLL_UP
 SCROLL_VIEW SET_ALERT_BUTTON_PROPERTY SET_ALERT_PROPERTY SET_APPLICATION_PROPERTY SET_BLOCK_PROPERTY
 SET_CANVAS_PROPERTY SET_CUSTOM_ITEM_PROPERTY SET_CUSTOM_PROPERTY SET_FORM_PROPERTY SET_GROUP_CHAR_CELL
 SET_GROUP_DATE_CELL SET_GROUP_NUMBER_CELL SET_GROUP_SELECTION SET_INPUT_FOCUS SET_ITEM_INSTANCE_PROPERTY
 SET_ITEM_PROPERTY SET_LOV_COLUMN_PROPERTY SET_LOV_PROPERTY SET_MENU_ITEM_PROPERTY SET_RADIO_BUTTON_PROPERTY
 SET_RECORD_PROPERTY SET_RELATION_PROPERTY SET_TAB_PAGE_PROPERTY SET_TREE_NODE_PROPERTY SET_TREE_PROPERTY
 SET_TREE_SELECTION SET_VA_PROPERTY SET_VIEW_PROPERTY SET_WINDOW_PROPERTY SHOW_ALERT SHOW_EDITOR SHOW_KEYS
 SHOW_LOV SHOW_MENU SHOW_VIEW SHOW_WINDOW SYNCHRONIZE TERMINATE UNSET_GROUP_SELECTION VALIDATE
 ADD_LIST_ELEMENT DELETE_LIST_ELEMENT ADD_TREE_DATA ADD_TREE_NODE DELETE_TREE_NODE FIND_TREE_NODE'''.split())

# Built-in packages: every routine of the package is a Forms built-in (a compiled
# form cannot reach a same-named database package without an owner prefix).
PACKAGES = {'WEB': 'ui', 'DEBUG': 'ui', 'LIST': 'ui', 'TOOL_ERR': 'ui', 'ORA_NLS': 'ui', 'ORA_PROF': 'ui',
            'PECS': 'ui', 'VBX': 'ui', 'FBEAN': 'ui', 'FTREE': 'server', 'TEXT_IO': 'server', 'TOOL_ENV': 'server',
            'TOOL_RES': 'server', 'OLE2': 'server', 'DDE': 'server', 'ORA_FFI': 'server', 'ORA_JAVA': 'server',
            'JNI': 'server', 'EXEC_SQL': 'server', 'FORMS_OLE': 'server'}

# Start-up triggers made only of these change nothing but the screen: they cannot set
# up authorization or query context (item/block properties are deliberately absent).
PRESENTATION = set('''GO_BLOCK GO_ITEM GO_RECORD GO_FORM NEXT_BLOCK PREVIOUS_BLOCK NEXT_ITEM PREVIOUS_ITEM
 NEXT_RECORD PREVIOUS_RECORD FIRST_RECORD LAST_RECORD UP DOWN SCROLL_UP SCROLL_DOWN SCROLL_VIEW SHOW_WINDOW
 HIDE_WINDOW MOVE_WINDOW RESIZE_WINDOW SET_WINDOW_PROPERTY SHOW_VIEW HIDE_VIEW SET_VIEW_PROPERTY
 SET_CANVAS_PROPERTY REPLACE_CONTENT_VIEW SET_APPLICATION_PROPERTY SET_INPUT_FOCUS SYNCHRONIZE REDISPLAY BELL
 MESSAGE CLEAR_MESSAGE EXECUTE_QUERY ENTER_QUERY'''.split())

# Forms constants that may appear as arguments; none of them evaluates anything.
CONSTANTS = set('''PROPERTY_TRUE PROPERTY_FALSE PROPERTY_ON PROPERTY_OFF NO_VALIDATE DO_COMMIT NO_COMMIT
 ASK_COMMIT FULL_ROLLBACK RESTRICT NO_RESTRICT ALL_RECORDS FOR_UPDATE NO_WAIT ENABLED VISIBLE DISPLAYED
 NAVIGABLE ENTERABLE UPDATE_ALLOWED INSERT_ALLOWED DELETE_ALLOWED QUERY_ALLOWED QUERYABLE REQUIRED
 UPDATE_NULL LABEL PROMPT_TEXT HINT_TEXT TOOLTIP_TEXT VISUAL_ATTRIBUTE CURRENT_RECORD_ATTRIBUTE
 BACKGROUND_COLOR FOREGROUND_COLOR FILL_PATTERN FONT_NAME FONT_SIZE FONT_STYLE FONT_WEIGHT FONT_SPACING
 POSITION X_POS Y_POS WIDTH HEIGHT TITLE WINDOW_STATE WINDOW_SIZE MAXIMIZE MINIMIZE NORMAL FORMS_MDI_WINDOW
 ROOT_WINDOW VIEWPORT_X_POS VIEWPORT_Y_POS TOPMOST_TAB_PAGE CURSOR_STYLE BUSY CROSSHAIR HELP INSERTION
 CURRENT_RECORD DEFAULT_WHERE ONETIME_WHERE ORDER_BY STATUS NEW_STATUS QUERY_STATUS INSERT_STATUS
 CHANGED_STATUS VALIDATION VALIDATION_UNIT ITEM_SCOPE RECORD_SCOPE BLOCK_SCOPE FORM_SCOPE ITEM_IS_VALID
 TEXT_PARAMETER DATA_PARAMETER HIDE NO_HIDE DO_REPLACE NO_REPLACE QUERY_ONLY NO_QUERY_ONLY SESSION NO_SESSION
 SHARE_LIBRARY_DATA NO_SHARE_LIBRARY_DATA ACTIVATE NO_ACTIVATE ALERT_MESSAGE_TEXT ALERT_BUTTON1
 ALERT_BUTTON2 ALERT_BUTTON3 GROUP_NAME LOV_NAME AUTO_SKIP CASE_RESTRICTION CONCEAL_DATA ICON_NAME
 IMAGE_DEPTH BORDER_BEVEL ALIGNMENT ENFORCE_KEY DIRECTION MAX_LENGTH FIXED_LENGTH'''.split())

# Side-effect-free functions: Forms getters and PL/SQL STANDARD functions.
PURE_FUNCTIONS = set('''NAME_IN ID_NULL CHECKBOX_CHECKED FIND_ITEM FIND_BLOCK FIND_WINDOW FIND_CANVAS FIND_VIEW
 FIND_TAB_PAGE FIND_LOV FIND_ALERT FIND_GROUP FIND_COLUMN FIND_FORM FIND_TIMER FIND_RELATION FIND_EDITOR
 FIND_MENU_ITEM FIND_VA GET_ITEM_PROPERTY GET_ITEM_INSTANCE_PROPERTY GET_BLOCK_PROPERTY GET_FORM_PROPERTY
 GET_APPLICATION_PROPERTY GET_WINDOW_PROPERTY GET_CANVAS_PROPERTY GET_VIEW_PROPERTY GET_TAB_PAGE_PROPERTY
 GET_RECORD_PROPERTY GET_RELATION_PROPERTY GET_LOV_PROPERTY GET_RADIO_BUTTON_PROPERTY GET_MENU_ITEM_PROPERTY
 GET_PARAMETER_LIST GET_LIST_ELEMENT_COUNT GET_LIST_ELEMENT_LABEL GET_LIST_ELEMENT_VALUE UPPER LOWER INITCAP
 TRIM LTRIM RTRIM SUBSTR INSTR LENGTH REPLACE LPAD RPAD CONCAT NVL TO_CHAR TO_NUMBER TO_DATE TRUNC ROUND ABS
 MOD SIGN CEIL FLOOR GREATEST LEAST CHR ASCII ADD_MONTHS LAST_DAY MONTHS_BETWEEN'''.split())


def builtin(name) -> tuple[str, str] | None:
    """(kind, label) of a Forms built-in routine name (standalone or PKG.PROC), or None.

    A three-part name (OWNER.PKG.PROC) is always a database call.
    """
    parts = str(name or '').strip().upper().split('.')
    if len(parts) == 1:
        word = parts[0]
        for kind, names in (('data', DATA), ('server', SERVER), ('ui', UI)):
            if word in names:
                return kind, 'Forms beépített hívás'
        return None
    if len(parts) == 2 and parts[0] in PACKAGES:
        return PACKAGES[parts[0]], 'Forms beépített csomag'
    return None


def refusal(name) -> str:
    """The reason text of a built-in that cannot run in the database (same wording as before 4.9)."""
    found = builtin(name)
    label = found[1] if found else 'Forms beépített hívás'
    return label + ': ' + str(name).upper() + ' (az adatbázisban nem futtatható).'
